<?php return array (
  'modules.all' => 
  array (
    0 => 'System',
    1 => 'Backend',
    2 => 'Cms',
    3 => 'Editor',
    4 => 'Media',
    5 => 'Tailor',
  ),
  'plugins.all' => 
  array (
    'myclinic\\doctor' => 'myclinic/doctor',
    'myclinic\\hr' => 'myclinic/hr',
    'myclinic\\programs' => 'myclinic/programs',
    'myclinic\\services' => 'myclinic/services',
    'myclinic\\setting' => 'myclinic/setting',
    'myclinic\\social' => 'myclinic/social',
    'october\\demo' => 'october/demo',
    'pikanji\\agent' => 'pikanji/agent',
    'rainlab\\builder' => 'rainlab/builder',
    'rainlab\\googleanalytics' => 'rainlab/googleanalytics',
    'rainlab\\pages' => 'rainlab/pages',
    'rainlab\\sitemap-plugin-master' => 'rainlab/sitemap-plugin-master',
    'webula\\smallbackup' => 'webula/smallbackup',
  ),
  'sites.all' => 
  array (
    0 => 
    array (
      'id' => 1,
      'name' => 'Primary Site',
      'code' => 'primary',
      'sort_order' => 1,
      'is_custom_url' => 0,
      'app_url' => NULL,
      'theme' => 'myclinic',
      'locale' => NULL,
      'fallback_locale' => '',
      'timezone' => NULL,
      'is_host_restricted' => 0,
      'allow_hosts' => NULL,
      'is_prefixed' => 0,
      'route_prefix' => NULL,
      'is_styled' => 0,
      'color_foreground' => NULL,
      'color_background' => NULL,
      'is_role_restricted' => 0,
      'allow_roles' => NULL,
      'is_primary' => 1,
      'is_enabled' => 1,
      'is_enabled_edit' => 1,
      'created_at' => '2024-09-27 16:31:11',
      'updated_at' => '2024-09-27 16:31:11',
      'group_id' => NULL,
      'group' => NULL,
    ),
  ),
  'database.check' => true,
);